"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold blue)"

[directory]
style = "bold blue"
truncate_to_repo = false
truncation_length = 0
read_only = ""

[git_branch]
disabled = true

[git_status]
disabled = true

[git_state]
disabled = true