general.import = ["./dracula.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 16
padding.y = 16
decorations = "None"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 12
offset = { x = 0, y = 1 }
